apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: office-management-system #you app name but no caps
  annotations:
    version: "v0.0.1"
    description: "To manage office Information"
spec:
  components:
    - name: component #name your component 
      type: webservice
      properties:
        image: sahiljindal123/office-management  #name of your dockerimage on dockerhub
        ports:
        - port: 8000  #port u used at the time of deployment 
          expose: true
      traits:
      - type: napptive-ingress # Set to napptive-ingress      
        properties:
          name: nginx-ingress # (Optional) endpoint name can be anything 
          port: 8000 # (Required) port  where the service is listening for incomming connections.
          path: / # (Required) path to be exposed